[package]
name = "kvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.119"
errno = "0.2.8"
thiserror = "1.0.30"
byte-unit = "4.0.13"
